/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class application_MyClass */

#ifndef _Included_application_MyClass
#define _Included_application_MyClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     application_MyClass
 * Method:    myPrint
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_application_MyClass_myPrint
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
